name: Run daily task

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  daily:
    name: Daily Tasks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci --omit dev
      - run: npm run build
      - run: npm run daily